### ISSUE TITLE
Question about bugs

### ISSUE THREAD

**Issue by SamitHuang** [manuelsh/capsule-networks-pytorch#1]
Hi, your code is really helpful. When you mentioned "we found several bugs on them", does "them" include the implementation of the authors ?
(https://github.com/Sarasra/models/tree/984fbc754943c849c55a57923f4223099a1ff88c/research/capsules/models)

**Comment by manuelsh** [comment]
Thanks Samit. We didn't review in detail the implementation of the authors (in TF), but mainly other PyTorch implementations.
